# Generated by Django 5.2.7 on 2025-10-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('userurl', models.URLField()),
            ],
        ),
    ]
