# Generated by Django 5.2.7 on 2025-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='userurl',
            field=models.URLField(max_length=255),
        ),
    ]
